options:
  formatter: stylish
  merge-default-rules: false
files:
  include: 'scss/**/*.scss'
rules:
  # Extends
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2

  # Mixins
  mixins-before-declarations:
    - 2
    -
      exclude:
        - 'mq'

  # Line Spacing
  empty-line-between-blocks: 2
  one-declaration-per-line: 2
  single-line-per-selector: 2

  # Disallows
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 2
  no-color-literals:
    - 2
    - allow-rgba: true
  no-combinators: 0
  no-css-comments: 0
  no-debug: 2
  no-disallowed-properties: 0
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements:
    - 2
    - allow-element-with-attribute: true
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 2
  no-universal-selectors: 0
  no-url-domains: 2
  no-vendor-prefixes: 2
  no-warn: 2
  property-units: 0

  # Nesting
  declarations-before-nesting: 2
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  nesting-depth:
    - 2
    -
      max-depth: 3

  # Name Formats
  class-name-format:
    - 2
    -
      convention: 'hyphenatedbem'
      allow-leading-underscore: false
  function-name-format: 2
  id-name-format:
    - 2
    -
      convention: 'hyphenatedlowercase'
      allow-leading-underscore: false
  mixin-name-format:
    - 2
    -
      convention: 'hyphenatedlowercase'
      allow-leading-underscore: false
  placeholder-name-format:
    - 2
    -
      convention: 'hyphenatedlowercase'
      allow-leading-underscore: false
  variable-name-format: 2

  # Style Guide
  attribute-quotes: 2
  bem-depth:
    - 2
    -
      max-depth: 3
  border-zero: 2
  brace-style: 2
  clean-import-paths: 2
  empty-args: 2
  hex-length: 2
  hex-notation: 2
  indentation: 2
  leading-zero: 2
  max-file-line-count:
    - 2
    -
      length: 400
  max-line-length:
    - 2
    -
      length: 120
  property-sort-order:
    - 2
    - order:
      - content
      - position
      - z-index
      - top
      - right
      - bottom
      - left
      - display
      - flex-flow
      - flex-direction
      - flex-wrap
      - justify-content
      - align-content
      - align-items
      - flex
      - flex-grow
      - flex-shrink
      - flex-basis
      - order
      - align-self
      - overflow
      - overflow-x
      - overflow-y
      - float
      - clear
      - box-sizing
      - width
      - min-width
      - max-width
      - height
      - min-height
      - max-height
      - margin
      - margin-top
      - margin-right
      - margin-bottom
      - margin-left
      - border
      - border-top
      - border-right
      - border-bottom
      - border-left
      - border-width
      - border-style
      - border-color
      - border-top-width
      - border-top-style
      - border-top-color
      - border-right-width
      - border-right-style
      - border-right-color
      - border-bottom-width
      - border-bottom-style
      - border-bottom-color
      - border-left-width
      - border-left-style
      - border-left-color
      - padding
      - padding-top
      - padding-right
      - padding-bottom
      - padding-left
      - box-shadow
      - outline
      - background
      - background-attachment
      - background-clip
      - background-color
      - background-image
      - background-origin
      - background-position
      - background-repeat
      - background-size
      - color
      - font
      - font-family
      - src
      - font-size
      - font-smoothing
      - font-style
      - font-variant
      - font-weight
      - line-height
      - text-align
      - text-decoration
      - text-indent
      - text-overflow
      - text-shadow
      - text-transform
      - white-space
      - letter-spacing
      - word-spacing
  pseudo-element: 2
  quotes: 2
  shorthand-values: 2
  url-quotes: 2
  variable-for-property: 2
  zero-unit: 2

  # Inner Spacing
  space-after-bang: 2
  space-after-colon: 2
  space-after-comma: 2
  space-around-operator: 2
  space-before-bang: 2
  space-before-brace: 2
  space-before-colon: 2
  space-between-parens: 2

  # Final Items
  final-newline: 2
  trailing-semicolon: 2
